sudo: required
services:
  - docker

before_install:
  - docker build -t zumrat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zumrat/react-test npm test -- --coverage

after_success:
  - docker build -t zumrat/multi-client -f ./client
  - docker build -t zumrat/multi-nginx -f ./nginx
  - docker build -t zumrat/multi-server -f ./server
  - docker build -t zumrat/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to push to docker hub
  - docker push -t zumrat/multi-client
  - docker push -t zumrat/multi-nginx
  - docker push -t zumrat/multi-server
  - docker push -t zumrat/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-956963432626
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
